name: test-ci-react

on:
  push:
    branches:
      - Nahush_dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use the latest version of Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: npm install, build, and test
        run: |
          cd extension
          npm install
          npm run build --if-present
