name: test-ci-react
on:
  push:
    branches:
      - Nahush_dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          cd extension/my_chrome_extension
          npm install
          npm run build --if-present